apiVersion: apps/v1
kind: Deployment 
metadata:
  name: spring-arguments-commands-deployment
spec:
  replicas: 1
  selector:
    matchLabels:      
      name: spring-arguments-commands-example
  template:
    metadata:
      labels:
        name: spring-arguments-commands-example
    spec:
      containers:
        - name: spring-arguments-commands-example
          image: patilashwin/spring-arguments-commands-example:1.0
          command:
            - ["sleep"]
          args:
            - ["20"]